#!/usr/bin/env bash

set -euo pipefail

function start-loading() {
  local fps="$1"
  while true
  do
    echo -ne "$(
      LC_ALL=true tr -dc 'a-t' </dev/urandom \
      | head -c "$( tput cols )" \
      | sed 'y/abcdefghijklmnopqrst/■▪▬▮▰◀◂▲▴▶▸◢◣◤◥◆▼●◖◗/'
    )\r"
    if (( fps > 0 ))
    then
      sleep "$( bc -l <<< "1/${fps}" )"
    fi
  done &
}

function stop-loading() {
  kill $!
  echo -ne '\r\033[K'
}

start-loading 10

mix stop

stop-loading
